export const GET_ARCADE_STATE = 'GET_ARCADE_STATE';
export const GET_ARCADE_STATE_PENDING = 'GET_ARCADE_STATE_PENDING';
export const GET_ARCADE_STATE_FULFILLED = 'GET_ARCADE_STATE_FULFILLED';
export const GET_ARCADE_STATE_REJECTED = 'GET_ARCADE_STATE_REJECTED';

export const GET_GAME_STATE = 'GET_GAME_STATE';
export const GET_GAME_STATE_PENDING = 'GET_GAME_STATE_PENDING';
export const GET_GAME_STATE_FULFILLED = 'GET_GAME_STATE_FULFILLED';
export const GET_GAME_STATE_REJECTED = 'GET_GAME_STATE_REJECTED';

export const MOVE = 'MOVE';
export const MOVE_PENDING = 'MOVE_PENDING';
export const MOVE_FULFILLED = 'MOVE_FULFILLED';
export const MOVE_REJECTED = 'MOVE_REJECTED';

export const UPLOAD = 'UPLOAD';
export const UPLOAD_PENDING = 'UPLOAD_PENDING';
export const UPLOAD_FULFILLED = 'UPLOAD_FULFILLED';
export const UPLOAD_REJECTED = 'UPLOAD_REJECTED';

export const HIDE_MESSAGE = 'HIDE_MESSAGE';
